require 'rubygems'
require 'rake'
require 'pathname'
require Pathname('lib/do_jdbc/postgres_version')

spec = Gem::Specification.new do |s|
  s.name              = 'do_jdbc-postgres'
  s.version           = DataObjects::Jdbc::Postgres::VERSION
  s.platform          = 'java'
  s.has_rdoc          = false
  s.extra_rdoc_files  = %w[ README BSD-LICENSE ]
  s.summary           = 'JDBC Driver for PostgreSQL, packaged as a Gem'
  s.description       = s.summary
  s.author            = ''
  s.email             = ''
  s.homepage          = ''
  s.require_path      = 'lib'
  s.files             = FileList[ '{lib}/**/*.{rb,jar}', 'Rakefile', *s.extra_rdoc_files ]
end

warn "#{spec.name} is only for use with JRuby" unless RUBY_PLATFORM =~ /java/
