require 'rubygems'
require 'rake'
require 'rake/clean'
require 'rake/gempackagetask'
require 'pathname'
require Pathname('lib/do_jdbc/h2_version')

CLEAN.include '{pkg}/'

spec = Gem::Specification.new do |s|
  s.name              = 'do_jdbc-h2'
  s.version           = DataObjects::Jdbc::H2::VERSION
  s.platform          = 'java'
  s.has_rdoc          = false
  s.extra_rdoc_files  = %w[ README H2-LICENSE EPL-LICENSE ]
  s.summary           = 'JDBC Driver for H2, packaged as a Gem'
  s.description       = s.summary
  s.author            = ''
  s.email             = ''
  s.homepage          = ''
  s.require_path      = 'lib'
  s.files             = FileList[ '{lib}/**/*.{rb,jar}', 'Rakefile', *s.extra_rdoc_files ]
end

warn "#{spec.name} is only for use with JRuby" unless RUBY_PLATFORM =~ /java/

task :default => [ :install ]

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end

desc "Install #{spec.name} #{spec.version}"
task :install =>  [ :package ] do
  sh %{jruby -S gem install --local pkg/#{spec.name}-#{spec.version} --no-update-sources}, :verbose => false
end
