require 'rubygems'
require 'rake'
require 'pathname'
require Pathname('lib/do_jdbc/h2_version')


ROOT = Pathname(__FILE__).dirname.expand_path

JRUBY = (RUBY_PLATFORM =~ /java/) rescue nil

AUTHOR = ""
EMAIL  = ""
GEM_NAME = "do_jdbc-h2"
GEM_VERSION = DataObjects::Jdbc::H2::VERSION
GEM_DEPENDENCIES = []
GEM_CLEAN = ['pkg', "**/.*.sw?", "*.gem", "*.gemspec", ".config", "**/.DS_Store"]
GEM_EXTRAS = { :platform => 'java', :has_rdoc => false }

PROJECT_NAME = "dorb"
PROJECT_URL  = "http://rubyforge.org/projects/dorb"
PROJECT_DESCRIPTION = PROJECT_SUMMARY = "JDBC Driver for H2, packaged as a Gem"

DRIVER = true

if (tasks_dir = ROOT.parent.parent + 'tasks').directory?
  require tasks_dir + 'hoe'
  require tasks_dir + 'gemspec_jruby'
end

warn "#{GEM_NAME} is only for use with JRuby" unless RUBY_PLATFORM =~ /java/

task :default => [ :install ]

desc "Install #{GEM_NAME} #{GEM_VERSION}"
task :install =>  [ :package ] do
  sh %{jruby -S gem install --local pkg/#{GEM_NAME}-#{GEM_VERSION} --no-update-sources}, :verbose => false
end
