require 'pathname'
require 'rubygems'
require 'rake'
require 'rake/rdoctask'
require 'spec/rake/spectask'
require 'lib/do_jdbc/version.rb'

ROOT    = Pathname(__FILE__).dirname.expand_path
JRUBY   = RUBY_PLATFORM =~ /java/
WINDOWS = Gem.win_platform?
SUDO    = (WINDOWS || JRUBY) ? '' : ('sudo' unless ENV['SUDOLESS'])

AUTHOR = "Alex Coles"
EMAIL  = "alex@alexcolesportfolio.com"
GEM_NAME = "do_jdbc"
GEM_VERSION = DataObjects::Jdbc::VERSION
GEM_DEPENDENCIES = [["data_objects", GEM_VERSION]]
GEM_CLEAN = ['build/*','dist/*','lib/**/*.jar']
GEM_EXTRAS = { :platform => 'java', :has_rdoc => false, :extra_rdoc_files => %w[ README.markdown MIT-LICENSE GPL-LICENSE ] }

PROJECT_NAME = "dorb"
PROJECT_URL  = "http://rubyforge.org/projects/dorb"
PROJECT_DESCRIPTION = PROJECT_SUMMARY = "JDBC support for DataObjects.rb drivers"


if (tasks_dir = ROOT.parent + 'tasks').directory?
  require tasks_dir + 'hoe'
  require tasks_dir + 'ext_helper_java'

  setup_java_extension  "#{GEM_NAME}_internal", HOE.spec,
    :source_dir => 'src/java', :add_buildr_task => false
end

def sudo_gem(cmd)
  sh "#{SUDO} #{RUBY} -S gem #{cmd}", :verbose => false
end

# Installation

task :default => [ :compile ]

task :filelist do
  puts FileList['pkg/**/*'].inspect
end

desc "Install #{GEM_NAME} #{GEM_VERSION}"
task :install => [ :package ] do
  sudo_gem "install pkg/#{GEM_NAME}-#{GEM_VERSION} --no-update-sources"
end

desc "Uninstall #{GEM_NAME} #{GEM_VERSION}"
task :uninstall => [ :clobber ] do
  sudo_gem "uninstall #{GEM_NAME} -v#{GEM_VERSION} -I -x"
end
