require 'rubygems'
require 'rake/gempackagetask'
require 'spec/rake/spectask'

WIN32 = (PLATFORM =~ /win32|cygwin/) rescue nil
SUDO  = WIN32 ? '' : ('sudo' unless ENV['SUDOLESS'])

spec = Gem::Specification.new do |s|
  s.name = "do_jdbc"
  s.version = "0.9.0"
  s.platform = Gem::Platform::RUBY
  s.has_rdoc = true
  s.extra_rdoc_files = ["README", "LICENSE", 'TODO']
  s.summary = "A DataObject.rb driver for JDBC"
  s.description = s.summary
  s.author = "Scott Bauer"
  s.email = "bauer.mail@gmail.com"
  s.homepage = "http://dataobjects.devjavu.com"
  s.add_dependency('data_objects', '>= 0.9.0')
  s.require_path = 'lib'
  s.autorequire = "do_jdbc"
  s.extensions = ["ext/extconf.rb"]
  s.files = %w(LICENSE README Rakefile TODO) + Dir.glob("{lib,specs,ext}/**/*").reject {|x| x =~ /\.(o|bundle)$/ }
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end

task :install => [:package] do
  sh %{#{SUDO} gem install --local pkg/#{spec.name}-#{spec.version} --no-update-sources}
end

desc "Run all specs in spec directory (excluding plugin specs)"
Spec::Rake::SpecTask.new(:spec) do |t|
  t.spec_opts = ['--options', "spec/spec.opts"] if File.exists?("spec/spec.opts")
  t.spec_files = FileList['spec/*_spec.rb']
end
