require 'pathname'
require 'rubygems'
require 'rake'
require 'rake/clean'

ROOT = Pathname(__FILE__).dirname.expand_path

require ROOT + 'lib/do_hsqldb/version'

JRUBY    = RUBY_PLATFORM =~ /java/
IRONRUBY = defined?(RUBY_ENGINE) && RUBY_ENGINE == 'ironruby'
WINDOWS  = Gem.win_platform? || (JRUBY && ENV_JAVA['os.name'] =~ /windows/i)
SUDO     = WINDOWS ? '' : ('sudo' unless ENV['SUDOLESS'])

CLEAN.include(%w[ {tmp,pkg}/ **/*.{o,so,bundle,jar,log,a,gem,dSYM,obj,pdb,exp,DS_Store,rbc,db} ext-java/target ])

begin
  require 'jeweler'

  task :build => [ :gemspec, 'lib/do_hsqldb_ext.jar' ]

  Jeweler::Tasks.new do |gem|
    gem.name        = 'do_hsqldb'
    gem.version     = DataObjects::Hsqldb::VERSION
    gem.summary     = 'DataObjects Hsqldb Driver'
    gem.description = 'Implements the DataObjects API for Hsqldb'
    gem.platform    = 'java'
    gem.files = FileList["lib/**/*.rb", "spec/**/*.rb", "tasks/**/*.rake",
                        "LICENSE", "Rakefile", "*.{markdown,rdoc,txt,yml}", "lib/*.jar"]

    gem.add_dependency "addressable", "~>2.1"
    gem.add_dependency "data_objects", DataObjects::Hsqldb::VERSION
    gem.add_dependency "jdbc-hsqldb", "~>1.8.0"
    gem.add_dependency "do_jdbc", DataObjects::Hsqldb::VERSION

    gem.add_development_dependency 'bacon', '~>1.1'

    gem.has_rdoc = false
    gem.rubyforge_project = 'dorb'
    gem.authors     = [ 'Alex Coles' ]
    gem.email       = 'alex@alexcolesportfolio.com'
  end

  Jeweler::RubyforgeTasks.new do |rubyforge|
    rubyforge.doc_task = 'yardoc'
  end
  Jeweler::GemcutterTasks.new

  FileList['tasks/**/*.rake'].each { |task| import task }
rescue LoadError
  puts 'Jeweler (or a dependency) not available. Install it with: gem install jeweler'
end
