source :rubygems

path '../'

gemspec

platforms :jruby do
  gem 'jdbc-sqlite3', '>=3.5.8'
  gem 'do_jdbc',      '0.10.12'
end

group :development do # Development dependencies (as in the gemspec)
  gem 'rake'
end
