require 'rubygems'
require 'rake'
require 'spec/rake/spectask'
require 'pathname'
require 'lib/do_derby/version'

ROOT = Pathname(__FILE__).dirname.expand_path

JRUBY = (RUBY_PLATFORM =~ /java/) rescue nil

AUTHOR = "Alex Coles"
EMAIL  = "alex@alexcolesportfolio.com"
GEM_NAME = "do_derby"
GEM_VERSION = DataObjects::Derby::VERSION
GEM_DEPENDENCIES = ["data_objects", GEM_VERSION], ["do_jdbc", GEM_VERSION], ["do_jdbc-derby", GEM_VERSION]
GEM_CLEAN = ['derby*', 'test.db.*','test/reports', 'test.sqlite3','lib/**/*.jar','manifest.mf']
GEM_EXTRAS = { :platform => 'java', :has_rdoc => false }

PROJECT_NAME = "dorb"
PROJECT_URL  = "http://rubyforge.org/projects/dorb"
PROJECT_DESCRIPTION = PROJECT_SUMMARY = "A DataObjects.rb driver for Derby"

DRIVER = true

require ROOT.parent + 'tasks/hoe'

task :default => [ :compile, :spec ]

task :install => [ :package ] do
  sh %{jruby -S gem install pkg/#{GEM_NAME}-#{GEM_VERSION} --no-update-sources}, :verbose => false
end

desc "Uninstall #{GEM_NAME} #{GEM_VERSION} (default ruby)"
task :uninstall => [ :clobber ] do
  sh "jruby -S gem uninstall #{GEM_NAME} -v#{GEM_VERSION} -I -x", :verbose => false
end

desc "Run specifications"
Spec::Rake::SpecTask.new('spec') do |t|
  t.spec_opts << '--options' << 'spec/spec.opts' if File.exists?('spec/spec.opts')
  t.spec_files = Pathname.glob((ROOT + 'spec/**/*_spec.rb').to_s)
end
