require 'rubygems'
require 'rake'
require 'rake/clean'
require 'rake/gempackagetask'
require 'spec/rake/spectask'
require 'pathname'
require Pathname(__FILE__).dirname.expand_path.parent + 'tasks/ext_helper_java'

# House-keeping
CLEAN.include 'derby*', 'test.db.*','test/reports', 'test.sqlite3','lib/**/*.jar','manifest.mf'

JRUBY = (RUBY_PLATFORM =~ /java/) rescue nil

spec = Gem::Specification.new do |s|
  s.name              = 'do_derby'
  s.version           = '0.9.3'
  s.platform          = 'java'
  s.has_rdoc          = false
  s.extra_rdoc_files  = %w[ README MIT-LICENSE TODO ]
  s.summary           = 'A DataObjects.rb driver for Derby'
  s.description       = s.summary
  s.author            = 'Alex Coles'
  s.email             = 'alex@alexcolesportfolio.com'
  s.homepage          = 'http://rubyforge.org/projects/dorb'
  s.require_path      = 'lib'

  s.files             = FileList[ '{lib,spec}/**/*.{class,rb}', 'Rakefile', *s.extra_rdoc_files ]
  s.add_dependency('data_objects',    "= #{s.version}")
  s.add_dependency('do_jdbc-support', "= #{s.version}")
  s.add_dependency('do_jdbc-derby')
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end

setup_extension_java "#{spec.name}_ext", spec

task :default => [ :compile, :spec ]

task :install => [ :package ] do
  sh %{jruby -S gem install pkg/#{spec.name}-#{spec.version} --no-update-sources}, :verbose => false
end

desc "Uninstall #{spec.name} #{spec.version} (default ruby)"
task :uninstall => [ :clobber ] do
  sh "jruby -S gem uninstall #{spec.name} -v#{spec.version} -I -x", :verbose => false
end

desc "Run specifications"
Spec::Rake::SpecTask.new('spec') do |t|
  t.spec_opts << '--options' << 'spec/spec.opts' if File.exists?('spec/spec.opts')
  t.spec_files = Pathname.glob(Pathname.new(__FILE__).dirname + 'spec/**/*_spec.rb')
end
