source :rubygems

gemspec

group :development do # Development dependencies (as in the gemspec)
  gem 'rake',       '~> 0.8.7'
  gem 'jeweler',    '~> 1.4'
end

group :quality do # These gems contain rake tasks that check the quality of the source code
  gem 'metric_fu',  '~> 1.3'
  gem 'rcov',       '~> 0.9.8'
  gem 'reek',       '~> 1.2.8'
  gem 'roodi',      '~> 2.1'
  gem 'yard',       '~> 0.5'
  gem 'yardstick',  '~> 0.1'
end
