require 'rubygems'
require 'spec'
require 'rake/gempackagetask'
require 'spec/rake/spectask'


GEM = "data_objects"
VERSION = "0.9.0"
AUTHOR = "Yehuda Katz"
EMAIL = "wycats@gmail.com"
HOMEPAGE = "http://dataobjects.devjavu.com"
SUMMARY = "The Core DataObjects class"

spec = Gem::Specification.new do |s|
  s.name = GEM
  s.version = VERSION
  s.platform = Gem::Platform::RUBY
  s.has_rdoc = true
  s.extra_rdoc_files = ["README", "LICENSE", 'TODO']
  s.summary = SUMMARY
  s.description = s.summary
  s.author = AUTHOR
  s.email = EMAIL
  s.homepage = HOMEPAGE
  s.require_path = 'lib'
  s.autorequire = GEM
  s.files = %w(LICENSE README Rakefile TODO) + Dir.glob("{lib,specs}/**/*")
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end

task :install => [:package] do
  sh %{#{'sudo' unless ENV['sudoless']} gem install pkg/#{GEM}-#{VERSION}}
end

desc "Run all specs in spec directory (excluding plugin specs)"
Spec::Rake::SpecTask.new(:spec) do |t|
  t.spec_opts = ['--options', "spec/spec.opts"] if File.exists?("spec/spec.opts")
  t.spec_files = FileList['spec/*_spec.rb']
end
