source :rubygems

path '../'

gemspec

platforms :jruby do
  gem 'jdbc-openedge', '>=10.1C'
  gem 'do_jdbc'
end

group :development do # Development dependencies (as in the gemspec)
  gem 'rake',     '~> 0.8.7'
end
