require 'rubygems'
require 'rake/gempackagetask'

PLUGIN = "do_mysql"
NAME = "do_mysql"
VERSION = "0.2.4"
AUTHOR = "Yehuda Katz"
EMAIL = "wycats@gmail.com"
HOMEPAGE = "http://dataobjects.devjavu.com"
SUMMARY = "A DataObject.rb driver for mysql"

spec = Gem::Specification.new do |s|
  s.name = NAME
  s.version = VERSION
  s.platform = Gem::Platform::RUBY
  s.has_rdoc = true
  s.extra_rdoc_files = ["README", "LICENSE", 'TODO']
  s.summary = SUMMARY
  s.description = s.summary
  s.author = AUTHOR
  s.email = EMAIL
  s.homepage = HOMEPAGE
  s.add_dependency('data_objects')
  s.require_path = 'lib'
  s.autorequire = PLUGIN
  s.extensions = ["ext/extconf.rb"]
  s.files = %w(LICENSE README Rakefile TODO) + Dir.glob("{lib,specs,ext}/**/*").reject {|x| x =~ /\.(o|bundle)$/ }
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end

task :install => [:package] do
  sh %{sudo gem install pkg/#{NAME}-#{VERSION}}
end

desc "Benchmark the RbyMysql library"
task :bench_rbmysql do

  $:.unshift 'lib'
  $:.unshift File.join('..', 'data_objects', 'lib')
  
  require 'data_objects'
  require 'rbmysql'
  require 'mysql'
  require 'benchmark'
  
    
  Benchmark.bm do |bm|

    widget_types = [
      Fixnum, String,String,String, String,String,String,String,String,String,
      FalseClass,Fixnum,Fixnum, Bignum,Float,Float,Float, Date,DateTime,DateTime,String
    ]

    ticket_types = [ Fixnum, String, Fixnum, DateTime, DateTime, Fixnum, Fixnum, Fixnum, String, Fixnum, Fixnum, Fixnum, DateTime, DateTime, TrueClass
    ]
    
    bm.report('RbMysql w/ set_types') do 
      connection = RbMysql::Connection.new('localhost', 'root', '', 'rbmysql_test', 3306, nil, nil)
      reader = connection.execute_reader("SELECT * FROM widget_types")
      reader.set_types widget_types
   
      until (row = reader.fetch_row).nil?
        row.each { |v| v } # Touch all the elements in the row, they've already been typecast
      end
     
      reader.close
      connection.close
    end
    
  end
end

task :bench_do do
  
  $:.unshift 'lib'
  $:.unshift File.join('..', 'data_objects', 'lib')
  
  require 'data_objects'
  require 'do_mysql'
  require 'active_record'
  require 'benchmark'
  
  Benchmark.bm do |bm|

      ActiveRecord::Base.establish_connection({
        :adapter => "mysql", 
        :host => "localhost",
        :user => 'root',
        :password => '',
        :database => 'rbmysql_test'
      })
    
    class Widget < ActiveRecord::Base
    end 
    
    bm.report("DataObjects::Mysql") do
      connection = DataObjects::Connection.new('mysql://root@localhost/rbmysql_test')
      
      1000.times do |t|  
        command = connection.create_command("SELECT * FROM widgets")

        # command.set_types [
        #   Fixnum, String,String,String, String,String,String,String,String,String,
        #     FalseClass,Fixnum,Fixnum, Bignum,Float,Float,Float, Date,DateTime,DateTime,String
        # ]

        reader = command.execute_reader

        until reader.eof?
          reader.values.each do |v|
            v # This is the type-cast field value
          end

          reader.next!
        end

        reader.close
      end
      
      connection.real_close
    end    

    bm.report('ActiveRecord') do
      1000.times do
        Widget.find(:all).each do |t|
          t.attribute_names.each do |a|
            t[a] # Touch the attribute to get AR to type-cast it
          end
        end
        
      end
    end
    
    
  end
end