require 'rubygems'
require 'rake/gempackagetask'

PLUGIN = "do_mysql"
NAME = "do_mysql"
VERSION = "0.2.4"
AUTHOR = "Yehuda Katz"
EMAIL = "wycats@gmail.com"
HOMEPAGE = "http://dataobjects.devjavu.com"
SUMMARY = "A DataObject.rb driver for mysql"

spec = Gem::Specification.new do |s|
  s.name = NAME
  s.version = VERSION
  s.platform = Gem::Platform::RUBY
  s.has_rdoc = true
  s.extra_rdoc_files = ["README", "LICENSE", 'TODO']
  s.summary = SUMMARY
  s.description = s.summary
  s.author = AUTHOR
  s.email = EMAIL
  s.homepage = HOMEPAGE
  s.add_dependency('data_objects')
  s.require_path = 'lib'
  s.autorequire = PLUGIN
  s.extensions = ["ext/extconf.rb"]
  s.files = %w(LICENSE README Rakefile TODO) + Dir.glob("{lib,specs,ext}/**/*").reject {|x| x =~ /\.(o|bundle)$/ }
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end

task :install => [:package] do
  sh %{sudo gem install pkg/#{NAME}-#{VERSION}}
end


task :benchmark do
  $:.push 'lib'
  require 'do_mysql'
  require 'benchmark'
  
  @connection = DataObject::Mysql::Connection.new('host=127.0.0.1 user=root dbname=rbmysql_test')
  @connection.open

  begin
    Benchmark.bm do |bm|
      bm.report do
          1000.times do |i|
            command = @connection.create_command('SELECT * FROM widgets')

            reader = command.execute_reader
            
            until (row = reader.next).nil?
              reader.field_count.times { |i|
                reader.item(i)
              }
            end
            # reader.close
          end
      end
    end
  ensure
    @connection.close
  end
  
end