package data_objects.drivers;

/**
 *
 * @author alexbcoles
 */
public interface DriverDefinition {
    
    /**
     * Whether the Driver supports properly supports JDBC 3.0's
     * autogenerated keys feature
     * 
     * @return
     */
    public boolean supportsJdbcGeneratedKeys();

}
