source :rubygems

path '../'

gemspec

platforms :jruby do
  gem 'jdbc-postgres', '>=8.2'
  gem 'do_jdbc',       '0.10.3'
end

group :development do # Development dependencies (as in the gemspec)
  gem 'rake',     '~> 0.8.7'
  gem 'jeweler',  '~> 1.4'
end
