require 'rubygems'
require 'rake'
require 'rake/clean'

require 'pathname'
require 'lib/do_postgres/version'

ROOT    = Pathname(__FILE__).dirname.expand_path
JRUBY   = RUBY_PLATFORM =~ /java/
WINDOWS = Gem.win_platform?
SUDO    = (WINDOWS || JRUBY) ? '' : ('sudo' unless ENV['SUDOLESS'])
BINARY_VERSION = '5.0.77'

Dir['tasks/*.rake'].each { |f| import f }

CLEAN.include(%w[**/*.rbc **/*.db **/*.{o,so,bundle,jar,log,a,gem,dSYM,obj,pdb,exp,DS_Store} ext/do_postgres_ext/Makefile ext-java/target tmp])
